### ISSUE TITLE
why is there only object per image?

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#10]
what if I label more target in one image when training?
is that ok for the code?

**Comment by kaankara** [comment]
The current model does not support that, since the contest data set has only one object to be detected per image. You need to change the last couple of layers and the loss function to support that. You can refer to the first YOLO paper (https://pjreddie.com/media/files/papers/yolo_1.pdf) to see how the loss function looks like.

**Comment by vxgu86** [comment]
all right. but I am still trying without success. wish me good luck...
