### ISSUE TITLE
halfsqueezenet training

### ISSUE THREAD

**Issue by ghost** [fpgasystems/spooNN#6]
Hi, 

I am trying to train the `halfsqueezenet  cnn` using my own dataset 
The following is what I have down

1. I have resized training images to 640x480.
2. I made `.xml` files for every training image.
3. I modified the [https://github.com/fpgasystems/spooNN/blob/master/halfsqueezenet/training/halfsqueezenet_objdetect.py#L67](url) to my dataset class.
4. mkdir `DAC18_object_detection_dataset` and organized my dataset as following
```
.
├── DAC18_object_detection_dataset
│   ├── boat
│   │   ├── 1.jpg
│   │   ├── 2.jpg
│   │   ├── 3.jpg
│   │   ├── 4.jpg
│   │   └── 5.jpg
│   └── building
│       ├── 1.jpg
│       ├── 2.jpg
│       ├── 3.jpg
│       ├── 4.jpg
│       └── 5.jpg
...
```

- **Is this flow right?**
- And I didn't figure out where I should put `.xml` files.
- I have noticed the `DEMO_DATASET ` was set to 1. It seems to have connection with testset,  if you could explain the `DEMO_DATASET ` and `all_classes`?

thanks

**Comment by kaankara** [comment]
Hi,
- This flow is correct. You just need to put the .xml files in the same directory as the images.
I would check if what you are reading is indeed correct by uncommenting line 207 and 228 in halfsqueezenet_objdetect.py
- You can change DEMO_DATASET to 0. This was added due to training for a specific dataset for a live demo, which had different resolution.

**Comment by KDUNAS** [comment]
Thank you. Here is the dataset [link.](https://github.com/xyzxinyizhang/2018-DAC-System-Design-Contest)
